db:
  nosql:
    url: mongodb://10.10.10.10:27017
    name: gg
  sql: "mysql+pymysql://root:galaxygallery@10.10.10.10:3306/gg"

site:
  name: "Galaxy Gallery Private Tracker"
  short: "[GGPT]"
  torrent_unique_key: "[GGPT]"
  domain: ['http://localhost:8080', 'https://pt.galaxy.gallery', 'https://6kj6r17qk.csb.app/'] # for CORS checking
  SECRET_KEY: c3ff4f4c36ab0bcd483e8bd76fbc5d43a8a76b71a582db1f96561e084be437ae
  ALGORITHM: HS256
  default:
    expire_minutes: 30
  email:
    sender: galaxygallery_no_reply@hotmail.com
    host: smtp.office365.com
    port: 587
  preference:
    per_page: 30
    reseed_threshold: 30 # unit days

client:
  baned_ports:
    [
        22,  # SSH Port
        53,  # DNS queries
        80, 81, 8080, 8081, # Hyper Text Transfer Protocol (HTTP) - port used for web traffic
        411, 412, 413,  # Direct Connect Hub (unofficial)
        443, 8443,  # HTTPS / SSL - encrypted web traffic, also used for VPN tunnels over HTTPS.
        1214,  # Kazaa - peer-to-peer file sharing, some known vulnerabilities, and at least one worm (Benjamin) targeting it.
        3389,  # IANA registered for Microsoft WBT Server, used for Windows Remote Desktop and Remote Assistance connections
        4662,  # eDonkey 2000 P2P file sharing service. http://www.edonkey2000.com/
        6346, 6347,  # Gnutella (FrostWire, Limewire, Shareaza, etc.), BearShare file sharing app
        6699,  # Port used by p2p software, such as WinMX, Napster.
        6881, 6882, 6883, 6884, 6885, 6886, 6887, 6888, 6889, 6890 # BitTorrent part of full range of ports used most often (unofficial)
    ]

cache:
  redis:
    host: 10.10.10.10
    port: 6379
  utils:
    checker:
      ip_checker:
        _check_db: null # maxsize = None
      ua_checker:
        _check_db: null # maxsize = None
  models:
    user:
      user:
        get_user_by_id:
          ttl: 60
        get_userid_by_passkey:
          ttl: 60
    torrent:
      peer:
        _get_peer_count:
          ttl: 60           # peer count update per 30 seconds
      torrent:
        _get_torrent_list: 
          ttl: 30
        get_torrent_info_hash: null
        get_torrent_id: null
      user_peer_stat: 
        get_last_action: 
          ttl: 86400
